language: cpp
before_install:
- openssl aes-256-cbc
  -K $encrypted_dc9ab2986818_key
  -iv $encrypted_dc9ab2986818_iv
  -in  config/travisci_rsa.enc
  -out config/travisci_rsa
  -d
- chmod 0600 config/travisci_rsa
- cp config/travisci_rsa ~/.ssh/id_rsa
- sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
- sudo apt-add-repository --yes ppa:boost-latest/ppa
- sudo apt-get update
install:
- sudo apt-get install --yes g++-4.8 libboost1.55-all-dev doxygen graphviz
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
script:
- make -j test USE_BOOST_REGEX=1
after_success:
- ./config/publish-doxygen