language: cpp
complier:
  - gcc
install:
  # Install GCC 4.8...
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install g++-4.8 -y
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
script: make test
